export const mockCards = [
  { id: '', text: 'What do you call crystal clear urine', answer: '1080pee.' },
  { id: '', text: 'What was Forrest Gump’s email password', answer: '1forrest1.' },
  { id: '', text: 'What does a house wear', answer: 'A dress.' },
  { id: '', text: 'What do you call a bear with no teeth', answer: 'A gummy bear.' },
  { id: '', text: 'What do you call a young musician', answer: 'A minor.' },
  { id: '', text: 'What do you call a line of rabbits marching backwards', answer: 'A receding hairline.' },
  { id: '', text: 'What do you call a belt with a watch on it', answer: 'A waist of time.' },
  { id: '', text: 'What do you call a fake noodle', answer: 'An Impasta.' },
  { id: '', text: 'How much does a hipster weigh', answer: 'An instagram.' },
  { id: '', text: 'Why is Kylo Ren so angry', answer: 'Beause he’s always Ben Solo.' },
  { id: '', text: 'Why does Superman gets invited to dinners', answer: 'Because he is a Supperhero.' },
  { id: '', text: 'Why didn’t the lion win the race', answer: 'Because he was racing a cheetah.' },
  { id: '', text: 'Why did the cookie cry', answer: 'Because his father was a wafer so long!' },
  { id: '', text: 'Why did the tomato turn red', answer: 'Because it saw the salad dressing.' },
  { id: '', text: 'Why did the octopus beat the shark in a fight', answer: 'Because it was well armed.' },
  { id: '', text: 'Why can’t you take inventory in Afghanistan', answer: 'Because of the tally ban.' },
  { id: '', text: 'Why are there fences on graveyards', answer: 'Because people are dying to get in.' },
  { id: '', text: 'Why did one banana spy on the other', answer: 'Because she was appealing.' },
  { id: '', text: 'Why don’t some couples go to the gym', answer: 'Because some relationships don’t work out.' },
  { id: '', text: 'Why isn’t suntanning an Olympic sport', answer: 'Because the best you can ever get is bronze.' },
  { id: '', text: 'Why don’t cannibals eat clowns', answer: 'Because they taste funny.' },
  { id: '', text: 'Is your refrigerator running', answer: 'Better go catch it.' },
  { id: '', text: 'What did the Buffalo say to his little boy when he dropped him off at school', answer: 'Bison.' },
  { id: '', text: 'Why does the man want to buy nine rackets', answer: 'Cause tennis too many.' },
  { id: '', text: 'What do prisoners use to call each other', answer: 'Cell phones.' },
  { id: '', text: 'What do cows tell each other at bedtime', answer: 'Dairy tales.' },
  { id: '', text: 'What’s it called when you have too many aliens', answer: 'Extraterrestrials.' },
  { id: '', text: 'What do you call a beautiful pumpkin', answer: 'GOURDgeous.' },
  { id: '', text: 'What do you call a cow with no legs', answer: 'Ground beef.' },
  { id: '', text: 'What do you call Samsung\'s security guards', answer: 'Guardians of the Galaxy.' },
  { id: '', text: 'Why was dumbo sad', answer: 'He felt irrelephant.' },
  { id: '', text: 'Why did the lion eat the tightrope walker', answer: 'He wanted a well-balanced meal!' },
  { id: '', text: 'Did you hear about the guy who lost the left side of his body', answer: 'He\'s alright now.' },
  { id: '', text: 'How does Moses make coffee', answer: 'Hebrews it.' },
  { id: '', text: 'What do you call a cow with all of its legs', answer: 'High steaks.' },
  { id: '', text: 'How does a penguin build it’s house', answer: 'Igloos it together.' },
  { id: '', text: 'What do you call a girl with one leg that\'s shorter than the other', answer: 'Ilene.' },
  { id: '', text: 'Where do you imprison a skeleton', answer: 'In a rib cage.' },
  { id: '', text: 'What happens to nitrogen when the sun comes up', answer: 'It becomes daytrogen.' },
  { id: '', text: 'Did you hear about the circus that caught on fire', answer: 'It was in tents.' },
  { id: '', text: 'Did you hear about the invention of the white board', answer: 'It was remarkable.' },
  { id: '', text: 'Did you hear about the crime in the parking garage', answer: 'It was wrong on so many levels.' },
  { id: '', text: 'Have you ever tried to eat a clock', answer: 'It\'s very time consuming.' },
  { id: '', text: 'So what if I don’t know what apocalypse means', answer: 'It’s not the end of the world!' },
  { id: '', text: 'What do you mean June is over', answer: 'Julying.' },
  { id: '', text: 'What does Superman have in his drink', answer: 'Just ice.' },
  { id: '', text: 'Why couldn’t the dead car drive into the cluttered garage', answer: 'Lack of vroom.' },
  { id: '', text: 'What do you call a cow with two legs', answer: 'Lean beef.' },
  { id: '', text: 'What do you receive when you ask a lemon for help', answer: 'Lemonaid.' },
  { id: '', text: 'I got hit in the head with a can of soda', answer: 'Luckily it was a soft drink.' },
  { id: '', text: 'What’s america’s favorite soda', answer: 'Mini soda.' },
  { id: '', text: 'What cheese can never be yours', answer: 'Nacho cheese.' },
  { id: '', text: 'Did you hear about the pun that was actually funny', answer: 'Neither have we.' },
  { id: '', text: 'Want to hear a joke about paper', answer: 'Nevermind it’s tearable.' },
  { id: '', text: 'Want to hear a pizza joke', answer: 'Nevermind', answer: 'it’s too cheesy.' },
  { id: '', text: 'Can February March', answer: 'No but April May.' },
  { id: '', text: 'What do you call a french pig', answer: 'Porque.' },
  { id: '', text: 'What’s it called when you put a cow in an elevator', answer: 'Raising the steaks.' },
  { id: '', text: 'What does a dog say when he sits down on a piece of sandpaper', answer: 'Ruff!' },
  { id: '', text: 'What planet is like a circus', answer: 'Saturn it has three rings!' },
  { id: '', text: 'What happened when the magician got mad', answer: 'She pulled her hare out!' },
  { id: '', text: 'Why can\'t bicycles stand up on their own', answer: 'Since they are 2 tired.' },
  { id: '', text: 'What kind of shoes do ninjas wear', answer: 'Sneakers.' },
  { id: '', text: 'What should you do if you are cold', answer: 'Stand in the corner. It’s 90 degrees.' },
  { id: '', text: 'What did the alien say to the pitcher of water', answer: 'Take me to your liter.' },
  { id: '', text: 'How many tickles does it take to make an octopus laugh', answer: 'Ten tickles.' },
  { id: '', text: 'Want to hear a pun about ghosts', answer: 'That\'s the spirit!' },
  { id: '', text: 'Do you know where you can get chicken broth in bulk', answer: 'The stock market.' },
  { id: '', text: 'What kind of car does a sheep drive', answer: 'Their SuBAHHru.' },
  { id: '', text: 'Why do trees have so many friends', answer: 'They branch out.' },
  { id: '', text: 'You know why I like egg puns', answer: 'They crack me up!' },
  { id: '', text: 'Why don’t vampires go to barbecues', answer: 'They don’t like steak.' },
  { id: '', text: 'Why are frogs so happy', answer: 'They eat whatever bugs them.' },
  { id: '', text: 'Why should you never trust a train', answer: 'They have loco motives.' },
  { id: '', text: 'How do trees access the internet', answer: 'They log on.' },
  { id: '', text: 'Why shouldn’t you trust atoms', answer: 'They make up everything.' },
  { id: '', text: 'Have you ever heard of a music group called Cellophane', answer: 'They mostly wrap.' },
  { id: '', text: 'How do mountains see', answer: 'They peak.' },
  { id: '', text: 'Did you hear about the human cannonball', answer: 'Too bad he got fired!' },
  { id: '', text: 'Have you ever tried to milk a cow which has been cut in half', answer: 'Udder madness.' },
  { id: '', text: 'When does a farmer dance', answer: 'When he drops the beet.' },
  { id: '', text: 'Why is metal and a microwave a match made in heaven', answer: 'When they met sparks flew.' },
  { id: '', text: 'How was Rome split in two', answer: 'With a pair of Ceasars.' },
  { id: '', text: 'What do you do with a dead chemist', answer: 'You barium.' },
  { id: '', text: 'Why is a skeleton a bad liar', answer: 'You can see right through it.' },
  { id: '', text: 'What do you do to an open wardrobe', answer: 'You closet.' },
  { id: '', text: 'What happens when you eat too many spaghettiOs', answer: 'You have a vowel movement.' },
  { id: '', text: 'What do you do when balloons are hurt', answer: 'You helium.' },
  { id: '', text: 'How do you organize an outer space party', answer: 'You planet.' },
  { id: '', text: 'Do you know sign language," You should learn it', answer: 'it’s pretty handy.' },
  { id: '', text: 'What did daddy spider say to baby spider', answer: 'You spend too much time on the web.' },
];